package elevator.view;

import elevator.Elevator;
import elevator.Event;
import elevator.EventListener;
import elevator.control.ControlEvent;
import java.awt.*;
import javax.swing.ImageIcon;
import javax.swing.border.MatteBorder;

public class View extends javax.swing.JFrame implements EventListener{

    /**
     * Creates new form Vista
     */
    private Elevator elevator;
    private final ImageIcon arrowDownOff = new ImageIcon(System.getProperty("user.dir")+"\\src\\elevator\\view\\img\\off-button-down.png");
    private final ImageIcon arrowDownOn = new ImageIcon(System.getProperty("user.dir")+"\\src\\elevator\\view\\img\\on-button-down.png");
    private final ImageIcon arrowUpOff = new ImageIcon(System.getProperty("user.dir")+"\\src\\elevator\\view\\img\\off-button-up.png");
    private final ImageIcon arrowUpOn = new ImageIcon(System.getProperty("user.dir")+"\\src\\elevator\\view\\img\\on-button-up.png");
    
    public View(Elevator elevator) {
        initComponents();
        this.elevator = elevator;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        cabin = new Cabin();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Down4 = new javax.swing.JButton();
        Up3 = new javax.swing.JButton();
        Down3 = new javax.swing.JButton();
        Up2 = new javax.swing.JButton();
        Down2 = new javax.swing.JButton();
        Up1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Floor4 = new javax.swing.JButton();
        Floor3 = new javax.swing.JButton();
        Floor2 = new javax.swing.JButton();
        Floor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 675));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(147, 191, 212));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setMaximumSize(new java.awt.Dimension(800, 800));
        jPanel5.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 650));

        cabin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cabin.setPreferredSize(new java.awt.Dimension(109, 150));

        javax.swing.GroupLayout cabinLayout = new javax.swing.GroupLayout(cabin);
        cabin.setLayout(cabinLayout);
        cabinLayout.setHorizontalGroup(
            cabinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );
        cabinLayout.setVerticalGroup(
            cabinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/cloud.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(30, 6));
        jLabel5.setMinimumSize(new java.awt.Dimension(30, 6));
        jLabel5.setPreferredSize(new java.awt.Dimension(30, 6));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/floor.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/cloud.png"))); // NOI18N
        jLabel7.setText("jLabel5");
        jLabel7.setMaximumSize(new java.awt.Dimension(30, 6));
        jLabel7.setMinimumSize(new java.awt.Dimension(30, 6));
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 6));

        jPanel3.setBackground(new java.awt.Color(184, 186, 186));
        jPanel3.setBorder(new MatteBorder(0, 0, 0, 1, new Color(100, 100, 100)));

        Down4.setBackground(new java.awt.Color(255, 255, 255));
        Down4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-down.png"))); // NOI18N
        Down4.setBorderPainted(false);
        Down4.setContentAreaFilled(false);
        Down4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Down4.setPreferredSize(new java.awt.Dimension(30, 30));
        Down4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Down4ActionPerformed(evt);
            }
        });

        Up3.setBackground(new java.awt.Color(255, 255, 255));
        Up3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-up.png"))); // NOI18N
        Up3.setBorderPainted(false);
        Up3.setContentAreaFilled(false);
        Up3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Up3.setPreferredSize(new java.awt.Dimension(30, 30));
        Up3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Up3ActionPerformed(evt);
            }
        });

        Down3.setBackground(new java.awt.Color(255, 255, 255));
        Down3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-down.png"))); // NOI18N
        Down3.setBorderPainted(false);
        Down3.setContentAreaFilled(false);
        Down3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Down3.setFocusPainted(false);
        Down3.setPreferredSize(new java.awt.Dimension(30, 30));
        Down3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Down3ActionPerformed(evt);
            }
        });

        Up2.setBackground(new java.awt.Color(255, 255, 255));
        Up2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-up.png"))); // NOI18N
        Up2.setBorderPainted(false);
        Up2.setContentAreaFilled(false);
        Up2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Up2.setPreferredSize(new java.awt.Dimension(30, 30));
        Up2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Up2ActionPerformed(evt);
            }
        });

        Down2.setBackground(new java.awt.Color(255, 255, 255));
        Down2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-down.png"))); // NOI18N
        Down2.setBorderPainted(false);
        Down2.setContentAreaFilled(false);
        Down2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Down2.setPreferredSize(new java.awt.Dimension(30, 30));
        Down2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Down2ActionPerformed(evt);
            }
        });

        Up1.setBackground(new java.awt.Color(255, 255, 255));
        Up1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-up.png"))); // NOI18N
        Up1.setBorderPainted(false);
        Up1.setContentAreaFilled(false);
        Up1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Up1.setPreferredSize(new java.awt.Dimension(30, 30));
        Up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Up1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Down4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Up1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Down2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Up2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Down3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Up3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Down4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(Up3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Down3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(Up2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Down2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(Up1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jPanel2.setBackground(new java.awt.Color(184, 186, 186));
        jPanel2.setBorder(new MatteBorder(0, 1, 0, 0, new Color(100, 100, 100)));

        jLabel8.setFont(new java.awt.Font("Stick No Bills", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("3");

        jLabel9.setFont(new java.awt.Font("Stick No Bills", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("4");

        jLabel10.setFont(new java.awt.Font("Stick No Bills", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("1");

        jLabel11.setFont(new java.awt.Font("Stick No Bills", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2");

        Floor4.setBackground(new java.awt.Color(255, 255, 255));
        Floor4.setForeground(new java.awt.Color(204, 255, 255));
        Floor4.setFocusPainted(false);
        Floor4.setFocusable(false);
        Floor4.setMaximumSize(new java.awt.Dimension(30, 6));
        Floor4.setMinimumSize(new java.awt.Dimension(30, 6));
        Floor4.setPreferredSize(new java.awt.Dimension(30, 6));
        Floor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Floor4ActionPerformed(evt);
            }
        });

        Floor3.setBackground(new java.awt.Color(255, 255, 255));
        Floor3.setForeground(new java.awt.Color(204, 255, 255));
        Floor3.setMaximumSize(new java.awt.Dimension(30, 30));
        Floor3.setMinimumSize(new java.awt.Dimension(15, 15));
        Floor3.setPreferredSize(new java.awt.Dimension(15, 15));
        Floor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Floor3ActionPerformed(evt);
            }
        });

        Floor2.setBackground(new java.awt.Color(255, 255, 255));
        Floor2.setForeground(new java.awt.Color(204, 255, 255));
        Floor2.setMaximumSize(new java.awt.Dimension(30, 6));
        Floor2.setMinimumSize(new java.awt.Dimension(30, 6));
        Floor2.setPreferredSize(new java.awt.Dimension(30, 6));
        Floor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Floor2ActionPerformed(evt);
            }
        });

        Floor1.setBackground(new java.awt.Color(255, 255, 255));
        Floor1.setForeground(new java.awt.Color(204, 255, 255));
        Floor1.setMaximumSize(new java.awt.Dimension(30, 6));
        Floor1.setMinimumSize(new java.awt.Dimension(30, 6));
        Floor1.setPreferredSize(new java.awt.Dimension(30, 6));
        Floor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Floor1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Floor4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Floor3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Floor2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Floor1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Floor4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Floor3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Floor2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Floor1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cabin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cabin, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Down4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Down4ActionPerformed
        Down4.setIcon(arrowDownOn);
        elevator.notify(new ControlEvent(4, false));
    }//GEN-LAST:event_Down4ActionPerformed

    private void Up3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Up3ActionPerformed
        Up3.setIcon(arrowUpOn);
        elevator.notify(new ControlEvent(3, true));
    }//GEN-LAST:event_Up3ActionPerformed

    private void Down3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Down3ActionPerformed
        Down3.setIcon(arrowDownOn);
        elevator.notify(new ControlEvent(3, false));
    }//GEN-LAST:event_Down3ActionPerformed

    private void Down2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Down2ActionPerformed
        Down2.setIcon(arrowDownOn);
        elevator.notify(new ControlEvent(2, false));
    }//GEN-LAST:event_Down2ActionPerformed

    private void Up2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Up2ActionPerformed
        Up2.setIcon(arrowUpOn);
        elevator.notify(new ControlEvent(2, true));
    }//GEN-LAST:event_Up2ActionPerformed

    private void Up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Up1ActionPerformed
        Up1.setIcon(arrowUpOn);
        elevator.notify(new ControlEvent(1, true));
    }//GEN-LAST:event_Up1ActionPerformed

    private void Floor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Floor3ActionPerformed
        // TODO add your handling code here:
        Floor3.setBackground(new Color(241,208,111));
        elevator.notify(new ControlEvent(3));
    }//GEN-LAST:event_Floor3ActionPerformed

    private void Floor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Floor2ActionPerformed
        // TODO add your handling code here:
        Floor2.setBackground(new Color(241,208,111));
        elevator.notify(new ControlEvent(2));
    }//GEN-LAST:event_Floor2ActionPerformed

    private void Floor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Floor1ActionPerformed
        // TODO add your handling code here:
        Floor1.setBackground(new Color(241,208,111));
        elevator.notify(new ControlEvent(1));
    }//GEN-LAST:event_Floor1ActionPerformed

    private void Floor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Floor4ActionPerformed
        // TODO add your handling code here:
        Floor4.setBackground(new Color(241,208,111));
        elevator.notify(new ControlEvent(4));
    }//GEN-LAST:event_Floor4ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Down2;
    private javax.swing.JButton Down3;
    private javax.swing.JButton Down4;
    private javax.swing.JButton Floor1;
    private javax.swing.JButton Floor2;
    private javax.swing.JButton Floor3;
    private javax.swing.JButton Floor4;
    private javax.swing.JButton Up1;
    private javax.swing.JButton Up2;
    private javax.swing.JButton Up3;
    /*
    private javax.swing.JPanel cabin;
    */
    Cabin cabin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notify(Event e) {
        ViewEvent event = (ViewEvent) e;
        switch(event.type){
            case STATE -> {
                cabin.refreshCabin(event.model.openedDoors, event.model.currentFloor);
            }
            case OUTSIDE_REQUESTS -> {
                if(event.up){
                    switch (event.floor+1) {
                        case 1 -> Up1.setIcon(arrowUpOff);
                        case 2 -> Up2.setIcon(arrowUpOff);
                        case 3 -> Up3.setIcon(arrowUpOff);
                    }
                } else {
                    switch (event.floor+1) {
                        case 2 -> Down2.setIcon(arrowDownOff);
                        case 3 -> Down3.setIcon(arrowDownOff);
                        case 4 -> Down4.setIcon(arrowDownOff);
                    }
                }
            }
            case INSIDE_REQUESTS -> {
                switch (event.floor+1) {
                    case 1 -> Floor1.setBackground(new Color(255,255,255));
                    case 2 -> Floor2.setBackground(new Color(255,255,255));
                    case 3 -> Floor3.setBackground(new Color(255,255,255));
                    case 4 -> Floor4.setBackground(new Color(255,255,255));
                }
            }
        }
    }
}
