package elevator.view;

import elevator.Elevator;
import elevator.Event;
import elevator.EventListener;
import elevator.control.ControlEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;

public class View extends javax.swing.JFrame implements EventListener{

    /**
     * Creates new form Vista
     */
    private Elevator elevator;
    private final ImageIcon arrowDownOff = new ImageIcon(System.getProperty("user.dir")+"\\src\\elevator\\view\\img\\off-button-down.png");
    private final ImageIcon arrowDownOn = new ImageIcon(System.getProperty("user.dir")+"\\src\\elevator\\view\\img\\on-button-down.png");
    private final ImageIcon arrowUpOff = new ImageIcon(System.getProperty("user.dir")+"\\src\\elevator\\view\\img\\off-button-up.png");
    private final ImageIcon arrowUpOn = new ImageIcon(System.getProperty("user.dir")+"\\src\\elevator\\view\\img\\on-button-up.png");
    
    public View(Elevator elevator) {
        initComponents();
        this.elevator = elevator;
        this.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        cabin = new Cabin();
        Down4 = new javax.swing.JButton();
        Up3 = new javax.swing.JButton();
        Down3 = new javax.swing.JButton();
        Up2 = new javax.swing.JButton();
        Down2 = new javax.swing.JButton();
        Up1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        insidePanel = new javax.swing.JPanel();
        Floor4 = new javax.swing.JButton();
        Floor3 = new javax.swing.JButton();
        Floor2 = new javax.swing.JButton();
        Floor1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        cabin.setPreferredSize(new java.awt.Dimension(109, 150));

        javax.swing.GroupLayout cabinLayout = new javax.swing.GroupLayout(cabin);
        cabin.setLayout(cabinLayout);
        cabinLayout.setHorizontalGroup(
            cabinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        cabinLayout.setVerticalGroup(
            cabinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        Down4.setBackground(new java.awt.Color(255, 255, 255));
        Down4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-down.png"))); // NOI18N
        Down4.setBorderPainted(false);
        Down4.setContentAreaFilled(false);
        Down4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Down4.setPreferredSize(new java.awt.Dimension(30, 30));
        Down4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Down4ActionPerformed(evt);
            }
        });

        Up3.setBackground(new java.awt.Color(255, 255, 255));
        Up3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-up.png"))); // NOI18N
        Up3.setBorderPainted(false);
        Up3.setContentAreaFilled(false);
        Up3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Up3.setPreferredSize(new java.awt.Dimension(30, 30));
        Up3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Up3ActionPerformed(evt);
            }
        });

        Down3.setBackground(new java.awt.Color(255, 255, 255));
        Down3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-down.png"))); // NOI18N
        Down3.setBorderPainted(false);
        Down3.setContentAreaFilled(false);
        Down3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Down3.setFocusPainted(false);
        Down3.setPreferredSize(new java.awt.Dimension(30, 30));
        Down3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Down3ActionPerformed(evt);
            }
        });

        Up2.setBackground(new java.awt.Color(255, 255, 255));
        Up2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-up.png"))); // NOI18N
        Up2.setBorderPainted(false);
        Up2.setContentAreaFilled(false);
        Up2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Up2.setPreferredSize(new java.awt.Dimension(30, 30));
        Up2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Up2ActionPerformed(evt);
            }
        });

        Down2.setBackground(new java.awt.Color(255, 255, 255));
        Down2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-down.png"))); // NOI18N
        Down2.setBorderPainted(false);
        Down2.setContentAreaFilled(false);
        Down2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Down2.setPreferredSize(new java.awt.Dimension(30, 30));
        Down2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Down2ActionPerformed(evt);
            }
        });

        Up1.setBackground(new java.awt.Color(255, 255, 255));
        Up1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elevator/view/img/off-button-up.png"))); // NOI18N
        Up1.setBorderPainted(false);
        Up1.setContentAreaFilled(false);
        Up1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Up1.setPreferredSize(new java.awt.Dimension(30, 30));
        Up1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Up1ActionPerformed(evt);
            }
        });

        insidePanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

        Floor4.setText("4");
        Floor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Floor4ActionPerformed(evt);
            }
        });
        insidePanel.add(Floor4);

        Floor3.setText("3");
        Floor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Floor3ActionPerformed(evt);
            }
        });
        insidePanel.add(Floor3);

        Floor2.setText("2");
        Floor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Floor2ActionPerformed(evt);
            }
        });
        insidePanel.add(Floor2);

        Floor1.setText("1");
        Floor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Floor1ActionPerformed(evt);
            }
        });
        insidePanel.add(Floor1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addComponent(insidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Down4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Down2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Up2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Up1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Up3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Down3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cabin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Down4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(Up3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Down3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Up2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Down2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Up1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cabin, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Down4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Down4ActionPerformed
        Down4.setIcon(arrowDownOn);
        elevator.notify(new ControlEvent(4, false));
    }//GEN-LAST:event_Down4ActionPerformed

    private void Up3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Up3ActionPerformed
        Up3.setIcon(arrowUpOn);
        elevator.notify(new ControlEvent(3, true));
    }//GEN-LAST:event_Up3ActionPerformed

    private void Down3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Down3ActionPerformed
        Down3.setIcon(arrowDownOn);
        elevator.notify(new ControlEvent(3, false));
    }//GEN-LAST:event_Down3ActionPerformed

    private void Down2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Down2ActionPerformed
        Down2.setIcon(arrowDownOn);
        elevator.notify(new ControlEvent(2, false));
    }//GEN-LAST:event_Down2ActionPerformed

    private void Up2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Up2ActionPerformed
        Up2.setIcon(arrowUpOn);
        elevator.notify(new ControlEvent(2, true));
    }//GEN-LAST:event_Up2ActionPerformed

    private void Up1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Up1ActionPerformed
        Up1.setIcon(arrowUpOn);
        elevator.notify(new ControlEvent(1, true));
    }//GEN-LAST:event_Up1ActionPerformed

    private void Floor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Floor4ActionPerformed
        // TODO add your handling code here:
        elevator.notify(new ControlEvent(4));
    }//GEN-LAST:event_Floor4ActionPerformed

    private void Floor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Floor3ActionPerformed
        // TODO add your handling code here:
        elevator.notify(new ControlEvent(3));
    }//GEN-LAST:event_Floor3ActionPerformed

    private void Floor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Floor2ActionPerformed
        // TODO add your handling code here:
        elevator.notify(new ControlEvent(2));
    }//GEN-LAST:event_Floor2ActionPerformed

    private void Floor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Floor1ActionPerformed
        // TODO add your handling code here:
        elevator.notify(new ControlEvent(1));
    }//GEN-LAST:event_Floor1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Down2;
    private javax.swing.JButton Down3;
    private javax.swing.JButton Down4;
    private javax.swing.JButton Floor1;
    private javax.swing.JButton Floor2;
    private javax.swing.JButton Floor3;
    private javax.swing.JButton Floor4;
    private javax.swing.JButton Up1;
    private javax.swing.JButton Up2;
    private javax.swing.JButton Up3;
    /*
    private javax.swing.JPanel cabin;
    */
    Cabin cabin;
    private javax.swing.JPanel insidePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notify(Event e) {
        ViewEvent event = (ViewEvent) e;
        switch(event.type){
            case STATE -> {
                cabin.refreshCabin(event.model.openedDoors, event.model.currentFloor);
            }
            case OUTSIDE_REQUESTS -> {
                if(event.up){
                    switch (event.floor+1) {
                        case 1 -> Up1.setIcon(arrowUpOff);
                        case 2 -> Up2.setIcon(arrowUpOff);
                        case 3 -> Up3.setIcon(arrowUpOff);
                    }
                } else {
                    switch (event.floor+1) {
                        case 2 -> Down2.setIcon(arrowDownOff);
                        case 3 -> Down3.setIcon(arrowDownOff);
                        case 4 -> Down4.setIcon(arrowDownOff);
                    }
                }
            }
            case INSIDE_REQUESTS -> {
                System.out.println("INSIDE REQUEST");
            }
        }
    }
}
